apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-express-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: express-server
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}